-- Table 1: kpi_qoe_aggregated (81 colonnes KPI agrégés)
CREATE TABLE public.kpi_qoe_aggregated (
  id BIGSERIAL PRIMARY KEY,
  date_part TEXT NOT NULL,
  dimension_1 TEXT NOT NULL,
  dimension_2 TEXT NOT NULL,
  volume_totale_dl DOUBLE PRECISION,
  volume_totale_ul DOUBLE PRECISION,
  volume_totale_totale DOUBLE PRECISION,
  debit_dl DOUBLE PRECISION,
  debit_dl_max DOUBLE PRECISION,
  debit_ul DOUBLE PRECISION,
  debit_ul_max DOUBLE PRECISION,
  rtt_setup_avg DOUBLE PRECISION,
  rtt_data_avg DOUBLE PRECISION,
  dms_debit_dl_3 DOUBLE PRECISION,
  dms_debit_dl_8 DOUBLE PRECISION,
  dms_debit_dl_30 DOUBLE PRECISION,
  dms_debit_ul_1 DOUBLE PRECISION,
  dms_debit_ul_3 DOUBLE PRECISION,
  dms_debit_ul_5 DOUBLE PRECISION,
  debit_dl_vol5 DOUBLE PRECISION,
  debit_ul_vol5 DOUBLE PRECISION,
  dms_3_dl_vol5 DOUBLE PRECISION,
  dms_8_dl_vol5 DOUBLE PRECISION,
  dms_30_dl_vol5 BIGINT,
  debit_dl_vol10 DOUBLE PRECISION,
  debit_ul_vol10 DOUBLE PRECISION,
  dms_3_dl_vol10 BIGINT,
  dms_8_dl_vol10 DOUBLE PRECISION,
  dms_30_dl_vol10 BIGINT,
  rtt_setup_0_40000 DOUBLE PRECISION,
  rtt_setup_40000_80000 DOUBLE PRECISION,
  rtt_setup_80000_150000 DOUBLE PRECISION,
  rtt_setup_150000_300000 DOUBLE PRECISION,
  rtt_setup_300000_inf BIGINT,
  rtt_data_0_40000 DOUBLE PRECISION,
  rtt_data_40000_80000 DOUBLE PRECISION,
  rtt_data_80000_150000 DOUBLE PRECISION,
  rtt_data_150000_300000 BIGINT,
  rtt_data_300000_inf BIGINT,
  loss_dl_rate DOUBLE PRECISION,
  loss_ul_rate DOUBLE PRECISION,
  tcp_retr_rate_dl DOUBLE PRECISION,
  tcp_retr_rate_ul DOUBLE PRECISION,
  "loss_dl_0_0.01" DOUBLE PRECISION,
  "loss_dl_0.01_0.03" DOUBLE PRECISION,
  "loss_dl_0.03_0.05" DOUBLE PRECISION,
  "loss_dl_0.05_inf" DOUBLE PRECISION,
  "loss_ul_0_0.01" DOUBLE PRECISION,
  "loss_ul_0.01_0.03" DOUBLE PRECISION,
  "loss_ul_0.03_0.05" DOUBLE PRECISION,
  "loss_ul_0.05_inf" DOUBLE PRECISION,
  "retr_dl_0_0.01" DOUBLE PRECISION,
  "retr_dl_0.01_0.03" DOUBLE PRECISION,
  "retr_dl_0.03_0.05" DOUBLE PRECISION,
  "retr_dl_0.05_inf" DOUBLE PRECISION,
  "retr_ul_0_0.01" DOUBLE PRECISION,
  "retr_ul_0.01_0.03" DOUBLE PRECISION,
  "retr_ul_0.03_0.05" DOUBLE PRECISION,
  "retr_ul_0.05_inf" DOUBLE PRECISION,
  session_nbr BIGINT,
  session_wifi_nbr BIGINT,
  session_3g2g_nbr BIGINT,
  session_4g_nbr BIGINT,
  session_5g_nbr BIGINT,
  session_dur_moy DOUBLE PRECISION,
  session_dcr DOUBLE PRECISION,
  out_of_order_nbr BIGINT,
  out_of_order_rate DOUBLE PRECISION,
  wind_full_nbr BIGINT,
  wind_full_rate DOUBLE PRECISION,
  "fallback_5G_to_4G_rate" DOUBLE PRECISION,
  "fallback_4G_to_3G2G_rate" DOUBLE PRECISION,
  instability_rate DOUBLE PRECISION,
  time_rat_5g_pct DOUBLE PRECISION,
  time_rat_4g_pct DOUBLE PRECISION,
  time_rat_3g2g_pct BIGINT,
  time_rat_wifi_pct BIGINT,
  "Mauvaise_Session_nbr" BIGINT,
  "Mauvaise_Session_Rate" DOUBLE PRECISION,
  qoe_index DOUBLE PRECISION,
  "5G_capable_rate" DOUBLE PRECISION,
  "5gue_attached_4G_rate" DOUBLE PRECISION,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(date_part, dimension_1, dimension_2)
);

CREATE INDEX idx_kqi_agg_date ON public.kpi_qoe_aggregated(date_part);
CREATE INDEX idx_kqi_agg_dim1 ON public.kpi_qoe_aggregated(dimension_1);
CREATE INDEX idx_kqi_agg_dim2 ON public.kpi_qoe_aggregated(dimension_2);

ALTER TABLE public.kpi_qoe_aggregated ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read kpi_qoe_aggregated" ON public.kpi_qoe_aggregated FOR SELECT USING (true);
CREATE POLICY "Allow public insert kpi_qoe_aggregated" ON public.kpi_qoe_aggregated FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update kpi_qoe_aggregated" ON public.kpi_qoe_aggregated FOR UPDATE USING (true);
CREATE POLICY "Allow public delete kpi_qoe_aggregated" ON public.kpi_qoe_aggregated FOR DELETE USING (true);

-- Table 2: ml_features (254 colonnes ML)
CREATE TABLE public.ml_features (
  id BIGSERIAL PRIMARY KEY,
  date_part TEXT NOT NULL,
  dimension_1 TEXT NOT NULL,
  dimension_2 TEXT NOT NULL,
  volume_totale_dl DOUBLE PRECISION,
  volume_totale_ul DOUBLE PRECISION,
  volume_totale_totale DOUBLE PRECISION,
  debit_dl DOUBLE PRECISION,
  debit_dl_max DOUBLE PRECISION,
  debit_ul DOUBLE PRECISION,
  debit_ul_max DOUBLE PRECISION,
  rtt_setup_avg DOUBLE PRECISION,
  rtt_data_avg DOUBLE PRECISION,
  dms_debit_dl_3 DOUBLE PRECISION,
  dms_debit_dl_8 DOUBLE PRECISION,
  dms_debit_dl_30 DOUBLE PRECISION,
  dms_debit_ul_1 DOUBLE PRECISION,
  dms_debit_ul_3 DOUBLE PRECISION,
  dms_debit_ul_5 DOUBLE PRECISION,
  debit_dl_vol5 DOUBLE PRECISION,
  debit_ul_vol5 DOUBLE PRECISION,
  dms_3_dl_vol5 DOUBLE PRECISION,
  dms_8_dl_vol5 DOUBLE PRECISION,
  dms_30_dl_vol5 BIGINT,
  debit_dl_vol10 DOUBLE PRECISION,
  debit_ul_vol10 DOUBLE PRECISION,
  dms_3_dl_vol10 BIGINT,
  dms_8_dl_vol10 DOUBLE PRECISION,
  dms_30_dl_vol10 BIGINT,
  rtt_setup_0_40000 DOUBLE PRECISION,
  rtt_setup_40000_80000 DOUBLE PRECISION,
  rtt_setup_80000_150000 DOUBLE PRECISION,
  rtt_setup_150000_300000 DOUBLE PRECISION,
  rtt_setup_300000_inf BIGINT,
  rtt_data_0_40000 DOUBLE PRECISION,
  rtt_data_40000_80000 DOUBLE PRECISION,
  rtt_data_80000_150000 DOUBLE PRECISION,
  rtt_data_150000_300000 BIGINT,
  rtt_data_300000_inf BIGINT,
  loss_dl_rate DOUBLE PRECISION,
  loss_ul_rate DOUBLE PRECISION,
  tcp_retr_rate_dl DOUBLE PRECISION,
  tcp_retr_rate_ul DOUBLE PRECISION,
  "loss_dl_0_0.01" DOUBLE PRECISION,
  "loss_dl_0.01_0.03" DOUBLE PRECISION,
  "loss_dl_0.03_0.05" DOUBLE PRECISION,
  "loss_dl_0.05_inf" DOUBLE PRECISION,
  "loss_ul_0_0.01" DOUBLE PRECISION,
  "loss_ul_0.01_0.03" DOUBLE PRECISION,
  "loss_ul_0.03_0.05" DOUBLE PRECISION,
  "loss_ul_0.05_inf" DOUBLE PRECISION,
  "retr_dl_0_0.01" DOUBLE PRECISION,
  "retr_dl_0.01_0.03" DOUBLE PRECISION,
  "retr_dl_0.03_0.05" DOUBLE PRECISION,
  "retr_dl_0.05_inf" DOUBLE PRECISION,
  "retr_ul_0_0.01" DOUBLE PRECISION,
  "retr_ul_0.01_0.03" DOUBLE PRECISION,
  "retr_ul_0.03_0.05" DOUBLE PRECISION,
  "retr_ul_0.05_inf" DOUBLE PRECISION,
  session_nbr BIGINT,
  session_wifi_nbr BIGINT,
  session_3g2g_nbr BIGINT,
  session_4g_nbr BIGINT,
  session_5g_nbr BIGINT,
  session_dur_moy DOUBLE PRECISION,
  session_dcr DOUBLE PRECISION,
  out_of_order_nbr BIGINT,
  out_of_order_rate DOUBLE PRECISION,
  wind_full_nbr BIGINT,
  wind_full_rate DOUBLE PRECISION,
  "fallback_5G_to_4G_rate" DOUBLE PRECISION,
  "fallback_4G_to_3G2G_rate" DOUBLE PRECISION,
  instability_rate DOUBLE PRECISION,
  time_rat_5g_pct DOUBLE PRECISION,
  time_rat_4g_pct DOUBLE PRECISION,
  time_rat_3g2g_pct BIGINT,
  time_rat_wifi_pct BIGINT,
  "Mauvaise_Session_nbr" BIGINT,
  "Mauvaise_Session_Rate" DOUBLE PRECISION,
  qoe_index DOUBLE PRECISION,
  "5G_capable_rate" DOUBLE PRECISION,
  "5gue_attached_4G_rate" DOUBLE PRECISION,
  debit_dl_delta7j_pct DOUBLE PRECISION,
  "debit_dl_J-7" DOUBLE PRECISION,
  debit_ul_delta7j_pct DOUBLE PRECISION,
  "debit_ul_J-7" DOUBLE PRECISION,
  rtt_setup_avg_delta7j_pct DOUBLE PRECISION,
  "rtt_setup_avg_J-7" DOUBLE PRECISION,
  rtt_data_avg_delta7j_pct DOUBLE PRECISION,
  "rtt_data_avg_J-7" DOUBLE PRECISION,
  loss_dl_rate_delta7j_pct DOUBLE PRECISION,
  "loss_dl_rate_J-7" DOUBLE PRECISION,
  loss_ul_rate_delta7j_pct DOUBLE PRECISION,
  "loss_ul_rate_J-7" DOUBLE PRECISION,
  tcp_retr_rate_dl_delta7j_pct DOUBLE PRECISION,
  "tcp_retr_rate_dl_J-7" DOUBLE PRECISION,
  tcp_retr_rate_ul_delta7j_pct DOUBLE PRECISION,
  "tcp_retr_rate_ul_J-7" DOUBLE PRECISION,
  session_nbr_delta7j_pct DOUBLE PRECISION,
  "session_nbr_J-7" BIGINT,
  session_dcr_delta7j_pct DOUBLE PRECISION,
  "session_dcr_J-7" DOUBLE PRECISION,
  qoe_index_delta7j_pct DOUBLE PRECISION,
  "qoe_index_J-7" DOUBLE PRECISION,
  "Mauvaise_Session_Rate_delta7j_pct" DOUBLE PRECISION,
  "Mauvaise_Session_Rate_J-7" DOUBLE PRECISION,
  dms_debit_dl_3_delta7j_pct DOUBLE PRECISION,
  "dms_debit_dl_3_J-7" DOUBLE PRECISION,
  dms_debit_dl_8_delta7j_pct DOUBLE PRECISION,
  "dms_debit_dl_8_J-7" DOUBLE PRECISION,
  dms_debit_dl_30_delta7j_pct DOUBLE PRECISION,
  "dms_debit_dl_30_J-7" DOUBLE PRECISION,
  dms_debit_ul_1_delta7j_pct DOUBLE PRECISION,
  "dms_debit_ul_1_J-7" DOUBLE PRECISION,
  dms_debit_ul_3_delta7j_pct DOUBLE PRECISION,
  "dms_debit_ul_3_J-7" DOUBLE PRECISION,
  dms_debit_ul_5_delta7j_pct DOUBLE PRECISION,
  "dms_debit_ul_5_J-7" DOUBLE PRECISION,
  out_of_order_rate_delta7j_pct DOUBLE PRECISION,
  "out_of_order_rate_J-7" DOUBLE PRECISION,
  wind_full_rate_delta7j_pct DOUBLE PRECISION,
  "wind_full_rate_J-7" DOUBLE PRECISION,
  "fallback_5G_to_4G_rate_delta7j_pct" DOUBLE PRECISION,
  "fallback_5G_to_4G_rate_J-7" DOUBLE PRECISION,
  instability_rate_delta7j_pct DOUBLE PRECISION,
  "instability_rate_J-7" DOUBLE PRECISION,
  time_rat_5g_pct_delta7j_pct DOUBLE PRECISION,
  "time_rat_5g_pct_J-7" DOUBLE PRECISION,
  time_rat_4g_pct_delta7j_pct DOUBLE PRECISION,
  "time_rat_4g_pct_J-7" DOUBLE PRECISION,
  volume_totale_dl_delta7j_pct DOUBLE PRECISION,
  "volume_totale_dl_J-7" DOUBLE PRECISION,
  volume_totale_ul_delta7j_pct DOUBLE PRECISION,
  "volume_totale_ul_J-7" DOUBLE PRECISION,
  session_dur_moy_delta7j_pct DOUBLE PRECISION,
  "session_dur_moy_J-7" DOUBLE PRECISION,
  debit_dl_delta14j_pct DOUBLE PRECISION,
  "debit_dl_J-14" DOUBLE PRECISION,
  debit_ul_delta14j_pct DOUBLE PRECISION,
  "debit_ul_J-14" DOUBLE PRECISION,
  rtt_setup_avg_delta14j_pct DOUBLE PRECISION,
  "rtt_setup_avg_J-14" DOUBLE PRECISION,
  rtt_data_avg_delta14j_pct DOUBLE PRECISION,
  "rtt_data_avg_J-14" DOUBLE PRECISION,
  loss_dl_rate_delta14j_pct DOUBLE PRECISION,
  "loss_dl_rate_J-14" DOUBLE PRECISION,
  loss_ul_rate_delta14j_pct DOUBLE PRECISION,
  "loss_ul_rate_J-14" DOUBLE PRECISION,
  tcp_retr_rate_dl_delta14j_pct DOUBLE PRECISION,
  "tcp_retr_rate_dl_J-14" DOUBLE PRECISION,
  tcp_retr_rate_ul_delta14j_pct DOUBLE PRECISION,
  "tcp_retr_rate_ul_J-14" DOUBLE PRECISION,
  session_nbr_delta14j_pct DOUBLE PRECISION,
  "session_nbr_J-14" BIGINT,
  session_dcr_delta14j_pct DOUBLE PRECISION,
  "session_dcr_J-14" DOUBLE PRECISION,
  qoe_index_delta14j_pct DOUBLE PRECISION,
  "qoe_index_J-14" DOUBLE PRECISION,
  "Mauvaise_Session_Rate_delta14j_pct" DOUBLE PRECISION,
  "Mauvaise_Session_Rate_J-14" DOUBLE PRECISION,
  dms_debit_dl_3_delta14j_pct DOUBLE PRECISION,
  "dms_debit_dl_3_J-14" DOUBLE PRECISION,
  dms_debit_dl_8_delta14j_pct DOUBLE PRECISION,
  "dms_debit_dl_8_J-14" DOUBLE PRECISION,
  dms_debit_dl_30_delta14j_pct DOUBLE PRECISION,
  "dms_debit_dl_30_J-14" DOUBLE PRECISION,
  dms_debit_ul_1_delta14j_pct DOUBLE PRECISION,
  "dms_debit_ul_1_J-14" DOUBLE PRECISION,
  dms_debit_ul_3_delta14j_pct DOUBLE PRECISION,
  "dms_debit_ul_3_J-14" DOUBLE PRECISION,
  dms_debit_ul_5_delta14j_pct DOUBLE PRECISION,
  "dms_debit_ul_5_J-14" DOUBLE PRECISION,
  out_of_order_rate_delta14j_pct DOUBLE PRECISION,
  "out_of_order_rate_J-14" DOUBLE PRECISION,
  wind_full_rate_delta14j_pct DOUBLE PRECISION,
  "wind_full_rate_J-14" DOUBLE PRECISION,
  "fallback_5G_to_4G_rate_delta14j_pct" DOUBLE PRECISION,
  "fallback_5G_to_4G_rate_J-14" DOUBLE PRECISION,
  instability_rate_delta14j_pct DOUBLE PRECISION,
  "instability_rate_J-14" DOUBLE PRECISION,
  time_rat_5g_pct_delta14j_pct DOUBLE PRECISION,
  "time_rat_5g_pct_J-14" DOUBLE PRECISION,
  time_rat_4g_pct_delta14j_pct DOUBLE PRECISION,
  "time_rat_4g_pct_J-14" DOUBLE PRECISION,
  volume_totale_dl_delta14j_pct DOUBLE PRECISION,
  "volume_totale_dl_J-14" DOUBLE PRECISION,
  volume_totale_ul_delta14j_pct DOUBLE PRECISION,
  "volume_totale_ul_J-14" DOUBLE PRECISION,
  session_dur_moy_delta14j_pct DOUBLE PRECISION,
  "session_dur_moy_J-14" DOUBLE PRECISION,
  score_debit DOUBLE PRECISION,
  score_latence DOUBLE PRECISION,
  score_loss DOUBLE PRECISION,
  score_retr DOUBLE PRECISION,
  score_stabilite DOUBLE PRECISION,
  score_drop DOUBLE PRECISION,
  score_dms DOUBLE PRECISION,
  qoe_composite DOUBLE PRECISION,
  trend_debit_dl TEXT,
  trend_rtt TEXT,
  trend_qoe TEXT,
  z_debit_dl DOUBLE PRECISION,
  pct_debit_dl DOUBLE PRECISION,
  z_debit_ul DOUBLE PRECISION,
  pct_debit_ul DOUBLE PRECISION,
  z_rtt_setup_avg DOUBLE PRECISION,
  pct_rtt_setup_avg DOUBLE PRECISION,
  z_rtt_data_avg DOUBLE PRECISION,
  pct_rtt_data_avg DOUBLE PRECISION,
  z_loss_dl_rate DOUBLE PRECISION,
  pct_loss_dl_rate DOUBLE PRECISION,
  z_loss_ul_rate DOUBLE PRECISION,
  pct_loss_ul_rate DOUBLE PRECISION,
  z_tcp_retr_rate_dl DOUBLE PRECISION,
  pct_tcp_retr_rate_dl DOUBLE PRECISION,
  z_tcp_retr_rate_ul DOUBLE PRECISION,
  pct_tcp_retr_rate_ul DOUBLE PRECISION,
  z_session_nbr DOUBLE PRECISION,
  pct_session_nbr DOUBLE PRECISION,
  z_session_dcr DOUBLE PRECISION,
  pct_session_dcr DOUBLE PRECISION,
  z_qoe_index DOUBLE PRECISION,
  pct_qoe_index DOUBLE PRECISION,
  "z_Mauvaise_Session_Rate" DOUBLE PRECISION,
  "pct_Mauvaise_Session_Rate" DOUBLE PRECISION,
  z_dms_debit_dl_3 DOUBLE PRECISION,
  pct_dms_debit_dl_3 DOUBLE PRECISION,
  z_dms_debit_dl_8 DOUBLE PRECISION,
  pct_dms_debit_dl_8 DOUBLE PRECISION,
  z_dms_debit_dl_30 DOUBLE PRECISION,
  pct_dms_debit_dl_30 DOUBLE PRECISION,
  z_dms_debit_ul_1 DOUBLE PRECISION,
  pct_dms_debit_ul_1 DOUBLE PRECISION,
  z_dms_debit_ul_3 DOUBLE PRECISION,
  pct_dms_debit_ul_3 DOUBLE PRECISION,
  z_dms_debit_ul_5 DOUBLE PRECISION,
  pct_dms_debit_ul_5 DOUBLE PRECISION,
  z_out_of_order_rate DOUBLE PRECISION,
  pct_out_of_order_rate DOUBLE PRECISION,
  z_wind_full_rate DOUBLE PRECISION,
  pct_wind_full_rate DOUBLE PRECISION,
  z_instability_rate DOUBLE PRECISION,
  pct_instability_rate DOUBLE PRECISION,
  z_time_rat_5g_pct DOUBLE PRECISION,
  pct_time_rat_5g_pct DOUBLE PRECISION,
  z_time_rat_4g_pct DOUBLE PRECISION,
  pct_time_rat_4g_pct DOUBLE PRECISION,
  z_volume_totale_dl DOUBLE PRECISION,
  pct_volume_totale_dl DOUBLE PRECISION,
  z_volume_totale_ul DOUBLE PRECISION,
  pct_volume_totale_ul DOUBLE PRECISION,
  z_session_dur_moy DOUBLE PRECISION,
  pct_session_dur_moy DOUBLE PRECISION,
  "z_fallback_5G_to_4G_rate" DOUBLE PRECISION,
  "pct_fallback_5G_to_4G_rate" DOUBLE PRECISION,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(date_part, dimension_1, dimension_2)
);

CREATE INDEX idx_ml_feat_date ON public.ml_features(date_part);
CREATE INDEX idx_ml_feat_dim1 ON public.ml_features(dimension_1);
CREATE INDEX idx_ml_feat_dim2 ON public.ml_features(dimension_2);

ALTER TABLE public.ml_features ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read ml_features" ON public.ml_features FOR SELECT USING (true);
CREATE POLICY "Allow public insert ml_features" ON public.ml_features FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update ml_features" ON public.ml_features FOR UPDATE USING (true);
CREATE POLICY "Allow public delete ml_features" ON public.ml_features FOR DELETE USING (true);